FROM php:7.4-apache

# Instalar dependências necessárias para a extensão mysqli
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd mysqli pdo pdo_mysql && \
    docker-php-ext-enable mysqli

# Habilitar mod_rewrite no Apache
RUN a2enmod rewrite

# Definir o diretório de trabalho
WORKDIR /var/www/html

# Copiar os arquivos da aplicação para o contêiner
COPY . /var/www/html/
